######################################################################################################################
#    _____  _       _   _     _      ___              _____             __ _       
#   |  __ \(_)     | | (_)   | |    / _ \            / ____|           / _(_)      
#   | |__) |_ _ __ | |_ _  __| | __| (_) |  ______  | |     ___  _ __ | |_ _  __ _ 
#   |  _  /| | '_ \| __| |/ _` |/ _ \__, | |______| | |    / _ \| '_ \|  _| |/ _` |
#   | | \ \| | |_) | |_| | (_| |  __/ / /           | |___| (_) | | | | | | | (_| |
#   |_|  \_\_| .__/ \__|_|\__,_|\___|/_/             \_____\___/|_| |_|_| |_|\__, |
#            | |                                                              __/ |
#            |_|                                                             |___/ 
######################################################################################################################

libraries:                                      # Library mappings must have a colon (:) placed after them 

######################################################################################################################
#    _________      __   _____ _                       
#   |__   __\ \    / /  / ____| |                      
#      | |   \ \  / /  | (___ | |__   _____      _____ 
#      | |    \ \/ /    \___ \| '_ \ / _ \ \ /\ / / __|
#      | |     \  /     ____) | | | | (_) \ V  V /\__ \
#      |_|      \/     |_____/|_| |_|\___/ \_/\_/ |___/
#                                                      
######################################################################################################################

  TV Shows:

    schedule_overlays: hourly(02-20)
    remove_overlays: false                      # Set this to true to remove all overlays
    reapply_overlays: false                     # This will reapply all overlays on each run, which will result in image bloat.
    #reset_overlays: plex                       # This will reset overlays to plex or tmdb Utill unless set to false                                      

    report_path: config/reports/TV_Report.yml

    #metadata_files:                            # Optional
    #- file: config/tv_refresh.yml

    collection_files:
    - file: config/TV_Collections.yml

    overlay_files:
    - file: config/TV_Overlays.yml
    - default: commonsense                      #content_rating_us_show
      template_variables:
        back_color: 00
        horizontal_align: left
        vertical_offset: 20
        vertical_align: bottom

    - default: commonsense                      #content_rating_us_show
      template_variables:
        overlay_level: season
        back_color: 00
        horizontal_align: left
        vertical_offset: 20
        vertical_align: bottom

    - default: commonsense                      #content_rating_us_show
      template_variables:
        overlay_level: episode
        back_color: 00
        horizontal_align: left
        vertical_offset: 20
        vertical_align: bottom

    - default: resolution
      template_variables:
        overlay_level: episode

    - default: runtimes
      template_variables:
        back_width: 300
        text: ''
        builder_level: episode

######################################################################################################################
#    _________      __   _____ _                          ____                       _   _                 
#   |__   __\ \    / /  / ____| |                        / __ \                     | | (_)                
#      | |   \ \  / /  | (___ | |__   _____      _____  | |  | |_ __   ___ _ __ __ _| |_ _  ___  _ __  ___ 
#      | |    \ \/ /    \___ \| '_ \ / _ \ \ /\ / / __| | |  | | '_ \ / _ \ '__/ _` | __| |/ _ \| '_ \/ __|
#      | |     \  /     ____) | | | | (_) \ V  V /\__ \ | |__| | |_) |  __/ | | (_| | |_| | (_) | | | \__ \
#      |_|      \/     |_____/|_| |_|\___/ \_/\_/ |___/  \____/| .__/ \___|_|  \__,_|\__|_|\___/|_| |_|___/
#                                                              | |                                         
#                                                              |_|                                         
######################################################################################################################

    operations:
      split_duplicates: false
      assets_for_all: false
      delete_unmanaged_collections: false       # Any manually added collection outside of PMM will be deleted
      delete_collections:                       # Deletes collections based on conditions below
        configured: false                       #False/True Removes all Managed Collections (Collections with the PMM Label) that are not configured in the Current Run.
        managed: true
        less: 1                                 # Collections with less than 1 movie/show in it will be deleted
       #managed: true                           # (Deletes PMM label Collections)                                           
       #managed: false                          # (Deletes no PMM label collections)                                          
       #configured: true                        # (Deletes collections in the config file)                                      
       #configured: false                       # (Deletes collections not in the config file)                                      
      mass_critic_rating_update: imdb           # Rating 2
      mass_audience_rating_update: tmdb         # mdb_tomoatoesaudience #mdb_metacritic # Rating 3
      mass_user_rating_update: mdb_tomatoes     # tmdb #Rating 1
        #mass_poster_update:                    # Updates every item's poster to the chosen sites poster. Will fall back to plex if the given option fails. Assets will be used over anything else.                                      
        #source: plex
        #seasons: true
        #episodes: true
      mass_episode_critic_rating_update: imdb
      mass_episode_audience_rating_update: tmdb
      mass_genre_update: tmdb
      mass_content_rating_update:
      - mdb_commonsense                         # Changes Content Rating to "1", "2" etc. to specify appropriate age
      - mdb_age_rating                          # Use MDbList Age Rating for Content Ratings      
      mass_originally_available_update: tmdb    # Update all original available date from tmdb (episode air date example)
      mass_imdb_parental_labels: none           # Updates all parental labels - Violence, Mild Nudity, Smoking, Foul Language, etc.


######################################################################################################################
#    __  __            _           
#   |  \/  |          (_)          
#   | \  / | _____   ___  ___  ___ 
#   | |\/| |/ _ \ \ / / |/ _ \/ __|
#   | |  | | (_) \ V /| |  __/\__ \
#   |_|  |_|\___/ \_/ |_|\___||___/
#                                  
#                                  
######################################################################################################################                            

  Movies:

    #schedule: hourly                           # (3) hour of day
    #schedule_overlays: hourly(02-20)
    remove_overlays: false                      # This will remove all overlays from your library every run, but will not delete the overlaid images from your system, resulting in image bloat.
    reapply_overlays: false                     # This will reapply all overlays on each run, which will result in image bloat.
    #reset_overlays: tmdb                       # This will reset overlays to plex or tmdb Utill set to false or removed this will reset all posters to the desired source on each run and will reapply all overlays on each run, which will result in image bloat.                                      
    report_path: config/reports/Movies_Report.yml

    #metadata_files:                            # Optonal
    #- file: config/movies_refresh.yml

    collection_files:
    - file: config/Movies_Collections.yml

    overlay_files:
    - file: config/Movies_Overlays.yml

    - default: mediastinger
      template_variables:
        horizontal_align: left
        vertical_align: top
        vertical_offset: 280

    - default: commonsense                      #content_rating_us_movie
      template_variables:
        back_color: 00
        horizontal_align: center
        horizontal_offset: 40
        vertical_align: bottom

######################################################################################################################
#    __  __            _              ____                       _   _                 
#   |  \/  |          (_)            / __ \                     | | (_)                
#   | \  / | _____   ___  ___  ___  | |  | |_ __   ___ _ __ __ _| |_ _  ___  _ __  ___ 
#   | |\/| |/ _ \ \ / / |/ _ \/ __| | |  | | '_ \ / _ \ '__/ _` | __| |/ _ \| '_ \/ __|
#   | |  | | (_) \ V /| |  __/\__ \ | |__| | |_) |  __/ | | (_| | |_| | (_) | | | \__ \
#   |_|  |_|\___/ \_/ |_|\___||___/  \____/| .__/ \___|_|  \__,_|\__|_|\___/|_| |_|___/
#                                          | |                                         
#                                          |_|                                         
######################################################################################################################

    operations:
      split_duplicates: false
      assets_for_all: false
      delete_unmanaged_collections: false       # Any manually added collection outside of PMM will be deleted
      delete_collections:                       # Deletes collections based on conditions below
        configured: false                       #False/True Removes all Managed Collections (Collections with the PMM Label) that are not configured in the Current Run.
        managed: true
        less: 1                                 # Collections with less than 1 movie/show in it will be deleted
        #managed: true                          # (Deletes PMM label Collections)                                           
        #managed: false                         # (Deletes no PMM label collections)                                          
        #configured: true                       # (Deletes collections in the config file)                                        
        #configured: false                      # (Deletes collections not in the config file)                                      
      #mass_poster_update: plex                 # Updates every item's poster to the chosen sites poster. Will fall back to plex if the given option fails. Assets will be used over anything else.                                 
      mass_critic_rating_update: imdb           # Rating 2
      mass_audience_rating_update: tmdb         # mdb_tomoatoesaudience #mdb_metacritic # Rating 3
      mass_user_rating_update: mdb_tomatoes     # tmdb #Rating 1   
      mass_genre_update: tmdb
      mass_content_rating_update:
      - mdb_commonsense                         # Changes Content Rating to "1", "2" etc. to specify appropriate age
      - mdb                                     # Use MdbList for Content Ratings
      - mdb_age_rating                          # Use MDbList Age Rating for Content Ratings
      - NR
      mass_originally_available_update: tmdb
      mass_imdb_parental_labels: none

######################################################################################################################
#     _____ _       _           _    _____      _   _   _                 
#    / ____| |     | |         | |  / ____|    | | | | (_)                
#   | |  __| | ___ | |__   __ _| | | (___   ___| |_| |_ _ _ __   __ _ ___ 
#   | | |_ | |/ _ \| '_ \ / _` | |  \___ \ / _ \ __| __| | '_ \ / _` / __|
#   | |__| | | (_) | |_) | (_| | |  ____) |  __/ |_| |_| | | | | (_| \__ \
#    \_____|_|\___/|_.__/ \__,_|_| |_____/ \___|\__|\__|_|_| |_|\__, |___/
#                                                                __/ |    
#                                                               |___/     
######################################################################################################################

settings:                                       # Can be individually specified per library as well
  assets_for_all: false
  asset_depth: 1
  asset_directory: plex/assets
  asset_folders: false
  cache: true
  cache_expiration: 60
  check_nightly: true
  create_asset_folders: false
  custom_repo:
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  dimensional_asset_rename: false
  download_url_assets: true
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  minimum_items: 1
  missing_only_released: false
  only_filter_missing: false
  overlay_artwork_filetype: jpg
  overlay_artwork_quality: 75
  playlist_exclude_users:
  playlist_report: false
  playlist_sync_to_user: all
  prioritize_assets: true
  released_missing_only: false
  run_again_delay: 5
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  save_missing: false
  save_report: false
  show_asset_not_needed: true
  show_filtered: false
  show_missing: true
  show_missing_assets: false
  show_missing_episode_assets: false
  show_missing_season_assets: false
  show_options: false
  show_unmanaged: true
  show_unconfigured: true
  sync_mode: sync                               #append # append/sync - append doesn't remove items from a collection - sync does
  tvdb_language: eng
  verify_ssl: true

######################################################################################################################
#     ____  _   _                  _____      _   _   _                 
#    / __ \| | | |                / ____|    | | | | (_)                
#   | |  | | |_| |__   ___ _ __  | (___   ___| |_| |_ _ _ __   __ _ ___ 
#   | |  | | __| '_ \ / _ \ '__|  \___ \ / _ \ __| __| | '_ \ / _` / __|
#   | |__| | |_| | | |  __/ |     ____) |  __/ |_| |_| | | | | (_| \__ \
#    \____/ \__|_| |_|\___|_|    |_____/ \___|\__|\__|_|_| |_|\__, |___/
#                                                              __/ |    
#                                                             |___/     
######################################################################################################################

webhooks:                                       # Can be individually specified per library as well
  version: https://discord.com/api/webhooks/<<DISCORDWEBHOOK>>
  run_start: https://discord.com/api/webhooks/<<DISCORDWEBHOOK>>
  run_end: https://discord.com/api/webhooks/<<DISCORDWEBHOOK>>
  changes: https://discord.com/api/webhooks/<<DISCORDWEBHOOK>>
  delete: https://discord.com/api/webhooks/<<DISCORDWEBHOOK>>
  error: https://discord.com/api/webhooks/<<DISCORDWEBHOOK>>

plex:                                           # Can be individually specified per library as well
  url: http://<<PLEXURL>>
  token: <<PLEXTOKEN>>
  timeout: 60
  clean_bundles: true
  empty_trash: false
  optimize: false
  db_cache:
  verify_ssl:

tmdb:                                           # Required for script to run
  apikey: <<TMDBAPI>>
  language: en
  cache_expiration: 60
  region:

tautulli:                                       # Can be individually specified per library as well
  url: http://<<TAUTULLIURL>>
  apikey: <<TAUTULLIAPI>>

omdb:
  apikey: <<OMDBAPI>>
  cache_expiration: 60

mdblist:
  apikey: <<MDBLISTAPI>>
  cache_expiration: 60

#notifiarr:
  #apikey: <<NOTIFIERAPI>>

radarr:                                         # Can be individually specified per library as well
  url: http://<<RADARRURL>>
  token: <<RADARRTOKEN>>
  add_missing: false
  add_existing: false
  root_folder_path: /movies
  monitor: true
  availability: announced
  quality_profile: Default HD-720/1080p
  tag:
  search: false
  radarr_path:
  plex_path:
  ignore_cache: false
  upgrade_existing: false
  monitor_existing: false

sonarr:                                         # Can be individually specified per library as well
  url: http://<<SONARRURL>>
  token: <<SONARRTOKEN>>
  add_missing: false
  add_existing: false
  root_folder_path: /TV
  monitor: all
  quality_profile: TV Default
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  sonarr_path:
  plex_path:
  ignore_cache: false
  upgrade_existing: false
  monitor_existing: false

trakt:
  client_id: <<TRAKTCLIENTID>>
  client_secret: <<TRAKTCLIENTSECRET>>
  pin:
  authorization:
#    _____              _ _     ______    _ _ _   
#   |  __ \            ( ) |   |  ____|  | (_) |  
#   | |  | | ___  _ __ |/| |_  | |__   __| |_| |_ 
#   | |  | |/ _ \| '_ \  | __| |  __| / _` | | __|
#   | |__| | (_) | | | | | |_  | |___| (_| | | |_ 
#   |_____/ \___/|_| |_|  \__| |______\__,_|_|\__|
#                                                 
                                                #   everything below is autofilled by the script

    access_token: 
    token_type: Bearer
    expires_in: 
    refresh_token: 
    scope: public
    created_at: 
  upgrade_existing: false

######################################################################################################################
#    ______ _   _ _____  
#   |  ____| \ | |  __ \ 
#   | |__  |  \| | |  | |
#   |  __| | . ` | |  | |
#   | |____| |\  | |__| |
#   |______|_| \_|_____/ 
#                        
######################################################################################################################
